### PR TITLE
Fixes for windows.

### PR DESCRIPTION
**Pull request by AntoineD**

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thanks for the contribution @AntoineD 

For the change of dependency, you may want to check https://github.com/Lucas-C/pre-commit-hooks/pull/18

Could please explain why the orher changes of encoding are needed?

**Comment by AntoineD** [comment]
Sure, sorry for the lack of context: under windows, if no encoding is defined then the platform default encoding is used, which is cp1252. Some utf8 characters cannot be decoded and I get the following error:

```python
  File "c:\users\antoined.cache\pre-commit\repos4usi0sm\py_env-default\lib\site-packages\pre_commit_hooks\insert_license.py", line 112, in process_files
    src_file_content = src_file.readlines()
  File "c:\users\antoined\tox\dev-win\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2704: character maps to <undefined>
```
in context managers with open.

**Comment by AntoineD** [comment]
Concerning the dependency, why not cutting a release that works on windows now, then cut a new one once the new dependency in #18 is released?

**Comment by Lucas-C** [comment]
On second thought, after checking that it still works under Cygwin and that [Virus Total does not report anything suspicious on the wheels](https://www.virustotal.com/gui/file/6b5c6e89a4e756ce32b66caf1bf4874a8419c8a323c85bf91dec1c8aadc92d6c/detection) published by Toby Harradine, I'm going to merge this

**Comment by Lucas-C** [comment]
Released: https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.1.10

**Pull request merged**
